### ISSUE TITLE
Search engine optimization

### ISSUE THREAD

**Issue by danielpopdan** [danielpopdan/drupal-community-cluj#170]
Caching Google Analytics' code can speed up page load times and increase your website's performance.

**Comment by prics** [comment]
Other issues:
2. Your page does not contain any H1 headings. H1 headings help indicate the important topics of your page to search engines. While less important than good meta-titles and descriptions, H1 headings may still help define the topic of your page to search engines. 
3. Your site lacks a sitemap file. Sitemaps can help robots index your content more thoroughly and quickly. Read more on Google's guidelines for implementing the sitemap protocol. 
4. Some of your website's JavaScript files are not minified! See full list of JavaScript files
5. Some of your website's CSS files are not minified! See full list of CSS files

Bonus:
6. Your webpage doesn't take the advantages of HTML Microdata specifications in order to markup structured data. View Google's guide for getting started with microdata.
7. Your DNS server is not using an SPF record. SPF (Sender Policy Framework) allows administrators to specify which hosts are allowed to send mail from a given domain by creating a specific SPF record or TXT record in the Domain Name System (DNS). You can find more information about SPF records here.
